version: 0.1.0.{build}
branches:
  only:
    - master

environment:
  DOTNETCLI_ZIP_URL: https://go.microsoft.com/fwlink/?LinkID=831469
  
install:
  - ps: (New-Object Net.WebClient).DownloadFile("$env:DOTNETCLI_ZIP_URL",'dotnet.zip')
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - echo %DOTNET_INSTALL_DIR%
  - ps: $env:DOTNET_INSTALL_DIR
  - 7z x dotnet.zip -y -o"%DOTNET_INSTALL_DIR%"
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
  - dotnet --info
          
build_script:
  - dotnet restore

test_script:
  - dotnet test test/ConsoleApp.test
